language: go

go:
    - "1.7.1"

branches:
  only:
    master


before_script:
    - npm i -g firebase firebase-tools@7.6.1
    - wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.61.0_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
    - tar -zxvf /tmp/hugo.tar.gz
    - export PATH=$PATH:$PWD/hugo_0.19_linux_amd64/


script:
    - git submodule update --init
    - hugo_0.19_linux_amd64


after_success:
    - firebase use myblog-alt --token ${FIREBASE_API_TOKEN}
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token ${FIREBASE_API_TOKEN}
